export const product = 'PRODUCT'
export const errorOccured = 'ERROR_OCCURED'
export const loginStatus = 'LOGIN_STATUS'
export const cart = 'CART'
export const productIncrement = 'PRODUCT_INCREMENT'
export const productDecrement = 'PRODUCT_DECREMENT'
export const cartDetails = 'CART_DETAILS'